#!/bin/bash

# Store the hostname we are copying the IP address for
hostname=$1

# Call tailscale status, pipe the output to grep to find the line with the hostname, pipe the output to awk to select the first column, and copy to clipboard
sudo tailscale status | grep $1 | awk '{print $1}' | tr -d '\n' | xclip -sel clip
